###User login
POST https://skill-sync-api-lnub.onrender.com/api/auth/signin
Content-Type: application/json

{
  "email": "drmosuhli1@gmail.com",
  "password": "1234"
}

### Create a user account
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "firstName": "Mabony",
  "lastName": "Mosuhli",
  "email": "drmosuhli40@gmail.com",
  "password": "1234",
  "confirmPassword": "1234"
}

### GET users details
GET https://skill-sync-api-lnub.onrender.com/api/user/list


### GET user details by id
GET http://localhost:3001/api/user/user-info/669cb6870b33297fa9dbea71


### Update a user by id
PATCH  http://localhost:3001/api/user/update/669f7b68f49638662696f2de
Content-Type: application/json

{
  "avatar": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
}


### Delete a user by id
DELETE  http://localhost:3001/api/user/delete/669cb6870b33297fa9dbea71

### Sign out a user
GET http://localhost:3001/api/auth/signout

### create a new user skills

POST http://localhost:3001/api/skills/create/669f708bf49638662696f281
Content-Type: application/json

{
  "skillsToTeach": [
    {
      "name": "C++",
      "yearsOfExperience": 5,
      "level": "Intermediate",
      "certifications": ["Certification1"],
      "description": "C++ is a JavaScript library for building user interfaces.",
      "tools": ["Tool1", "Tool2", "Tool3"],
      "projects": ["Project1", "Project2"]
    },
    {
      "name": "C#",
      "yearsOfExperience": 5,
      "level": "Intermediate",
      "certifications": ["Certification1"],
      "description": "C# is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
      "tools": ["Tool1", "Tool2", "Tool3"],
      "projects": ["Project1", "Project2"]
    },
    {
      "name": "Java",
      "yearsOfExperience": 5,
      "level": "Intermediate",
      "certifications": ["Certification1"],
      "description": "Java is a programming language that lets you work quickly and integrate systems more effectively.",
      "tools": ["Tool1", "Tool2", "Tool3"],
      "projects": ["Project1", "Project2"]
    }
  ],
  "skillsToLearn": ["React", "Node JS", "JavaScript"]
}

### Match the user with skills

GET http://localhost:3001/api/skills/matches/669cb6870b33297fa9dbea71

### send notifications

POST http://localhost:3001/api/notifications/send/669cb6680b33297fa9dbea6e
Content-Type: application/json
{
  "type": "like",
  "message": " on hghg fdd on hghg fdd on hghg f dd on hghg fdd fdd "
}

### get notifications

GET http://localhost:3001/api/notifications/list


### get notification By Id

GET http://localhost:3001/api/notifications/list/66a0d63aeda6a3465ca4ecaf

### mark notification as read

PATCH http://localhost:3001/api/notifications/66a0d374918573aa547203d9/read
Content-Type: application/json

{
  "message": "Halong with your network"
}
### get user's recommendations



































#hrXWgw4Q127uqZJ3