###User login
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email": "drmosuhli22322@gmail.com",
  "password": "2888"
}

### Create a user account
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "firstName": "Thato",
  "lastName": "Mosuhli",
  "email": "drmosuhli223422@gmail.com",
  "password": "2888",
  "confirmPassword": "2888"
}

### GET users details
GET http://localhost:3000/api/user/list


### GET user details by id
GET http://localhost:3000/products/668fa529f5dc7810e4cd74b8


### Update a user by id
PATCH  http://localhost:3000/api/user/update/6699282f228922109cc7633c
Content-Type: application/json

{
  "firstName": "Au"
}


### Delete a product by id
DELETE  http://localhost:3000/api/user/delete/669933a8618b742f94cd56b4

### 404 route Not Found
GET http://localhost:3000/abc_xyz



































#hrXWgw4Q127uqZJ3